# OLD/EXTRA ANALYSIS

```{r}
num_clusters <- 6
beta_matrix$cluster <- cutree(hclust_fit, k = num_clusters)

head(beta_matrix)

cluster_centroids <- beta_matrix %>%
    dplyr::group_by(cluster) %>%
    dplyr::summarise(across(everything(), mean))

cluster_centroids_long <- cluster_centroids %>%
    tidyr::gather(key = "group", value = "beta", -cluster)

cluster_centroids_long$group <- factor(cluster_centroids_long$group, levels = groups)
p <- ggplot(cluster_centroids_long, aes(x = group, y = beta, color = factor(cluster), group = cluster)) +
    geom_line(size = 1) +
    geom_point(size = 2) +
    scale_color_viridis_d(name = "Cluster") +
    theme_minimal() +
    labs(title = "Cluster Centroids of Beta Trajectories", x = "Group", y = "Beta") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1),
          axis.text.y = element_text(size = 12),
          plot.title = element_text(hjust = 0.5))
    # geom_line(data = beta_matrix_long, aes(x = group, y = beta, group = peak_gene_pair, color=factor(cluster)), 
    #           color = "gray", size = 0.3, alpha = 0.5, inherit.aes = FALSE) +
    # geom_line(size = 1) +
    # geom_point(size = 2)

centroid_plot_file <- file.path(plot_dir, "cluster_centroids_beta_trajectories_colored.jpg")
ggsave(centroid_plot_file, plot = p, width = 8, height = 6)

beta_matrix_long <- beta_matrix %>%
    tidyr::gather(key = "group", value = "beta", -peak_gene_pair)

p <- ggplot(beta_matrix_long, aes(x = group, y = beta)) +
    geom_point(alpha = 0.5) +
    theme_minimal() +
    labs(title = "Beta Values Across Groups",
         x = "Group",
         y = "Beta Value") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

beta_lines_plot_file <- file.path(plot_dir, "beta_values_dot_plot.jpg")
ggsave(beta_lines_plot_file, plot = p, width = 8, height = 6)
```

```{r}
set.seed(123)
n_iterations <- 100
spearman_correlations <- numeric(n_iterations)
slopes <- numeric(n_iterations)

for (i in 1:n_iterations) {
    boot_sample <- beta_matrix[sample(1:nrow(beta_matrix), replace = TRUE), ]
    
    boot_long <- boot_sample %>%
        tidyr::gather(key = "group", value = "beta", -peak_gene_pair) %>%
        mutate(group_numeric = as.numeric(factor(group, levels = groups)))
    
    spearman_correlations[i] <- cor(boot_long$group_numeric, boot_long$beta, method = "spearman")

    lm_model <- lm(beta ~ group_numeric, data = boot_long)
    slopes[i] <- coef(lm_model)[2]
}

cor_summary <- data.frame(
    mean_correlation = mean(spearman_correlations),
    lower_ci = quantile(spearman_correlations, 0.025),
    upper_ci = quantile(spearman_correlations, 0.975)
)

slopes_summary <- data.frame(
    mean_slope = mean(slopes),
    lower_ci = quantile(slopes, 0.025),
    upper_ci = quantile(slopes, 0.975)
)

print(cor_summary)
print(slopes_summary)

p <- ggplot(data.frame(correlation = spearman_correlations), aes(x = correlation)) +
    geom_histogram(bins = 30, fill = "lightblue", color = "black", alpha = 0.7) +
    labs(title = "Bootstrap Distribution of Spearman Correlations",
         x = "Spearman Correlation",
         y = "Frequency") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_text(hjust = 0.5))

spearman_hist_file <- file.path(plot_dir, "spearman_correlation_histogram.jpg")
ggsave(spearman_hist_file, plot = p, width = 8, height = 6)

```

```{r}
jaccard_values <- list()
groups <- c("First_trimester", "Second_trimester", "Third_trimester", "Infancy", "Adolescence")
for (group in groups) {
    scent_results_signif_mature_group <- scent_results_signif_mature[scent_results_signif_mature$group == group, ]
    peak_gene_pairs_group <- scent_results_signif_mature_group$peak_gene_pair
    jaccard_values[[group]] <- jaccard_index(peak_gene_pairs_mature_refgroup, peak_gene_pairs_group)
}

jaccard_values_df <- data.frame(group = names(jaccard_values), jaccard_index = unlist(jaccard_values))
jaccard_values_df$group <- factor(jaccard_values_df$group, levels = groups)

jaccard_values_df$group_numeric <- as.numeric(jaccard_values_df$group)
jaccard_model <- lm(jaccard_index ~ group_numeric, data = jaccard_values_df)
# jaccard_model <- lm(jaccard_index ~ group_numeric + num_cells, data = jaccard_values_df)
true_slope <- coef(jaccard_model)[2]

null_slopes <- c()
for (b in 1:500) {
    scent_results_signif_mature_permuted <- scent_results_signif_mature
    scent_results_signif_mature_permuted$group <- sample(scent_results_signif_mature_permuted$group, size = nrow(scent_results_signif_mature_permuted), replace = FALSE)

    jaccard_values <- list()
    for (group in groups) {
        scent_results_signif_mature_permuted_group <- scent_results_signif_mature_permuted[scent_results_signif_mature_permuted$group == group, ]
        peak_gene_pairs_group <- scent_results_signif_mature_permuted_group$peak_gene_pair
        jaccard_values[[group]] <- jaccard_index(peak_gene_pairs_mature_refgroup, peak_gene_pairs_group)
    }

    jaccard_values_df <- data.frame(group = names(jaccard_values), jaccard_index = unlist(jaccard_values))
    jaccard_values_df$group <- factor(jaccard_values_df$group, levels = groups)

    jaccard_values_df$group_numeric <- as.numeric(jaccard_values_df$group)
    jaccard_model <- lm(jaccard_index ~ group_numeric, data = jaccard_values_df)
    # jaccard_model <- lm(jaccard_index ~ group_numeric + num_cells, data = jaccard_values_df)
    null_slopes <- c(null_slopes, coef(jaccard_model)[2])
}

null_slopes_df <- data.frame(slope = null_slopes)
p <- ggplot(null_slopes_df, aes(x = slope)) +
    geom_histogram(bins = 30, fill = "lightblue", color = "black", alpha = 0.7) +
    geom_vline(xintercept = true_slope, color = "red", linetype = "dashed", size = 1) +
    labs(title = "Histogram of Null Slopes", 
         x = "Slope", 
         y = "Frequency") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_text(hjust = 0.5)) +
    annotate("text", x = true_slope, y = max(table(cut(null_slopes, breaks = 30))) * 0.9, 
             label = "True Slope", color = "red", hjust = -0.1)

histogram_file <- file.path(plot_dir, "null_slopes_histogram.jpg")
ggsave(histogram_file, plot = p, width = 8, height = 6)

p <- ggplot(jaccard_values_df, aes(x = group, y = jaccard_index)) +
    geom_point(size = 3, color = "blue") +
    geom_smooth(aes(x = group_numeric, y = jaccard_index), method = "lm", color = "red", se = FALSE) +
    theme_minimal() +
    labs(title = "Dotplot of Jaccard Index Across Groups",
         x = "Group",
         y = "Jaccard Index") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    ylim(0, 1)
dotplot_file <- file.path(plot_dir, "jaccard_index_dotplot_permuted.jpg")
ggsave(dotplot_file, plot = p, width = 8, height = 6)
```

```{r}
# changes in peaks for transcription factors CTIP2 and SATB2
plot_gene_beta_values <- function(gene, groups, celltypes, plot_dir, x="group") {

    gene_data <- scent_results_signif[scent_results_signif$gene == gene & 
                                      scent_results_signif$celltype %in% celltypes &
                                      scent_results_signif$group %in% groups,]                            
    
    dot_plot_data <- gene_data %>%
        dplyr::select(peak_gene_pair, celltype, group, beta, fdr)
    dot_plot_data$group <- factor(dot_plot_data$group, levels = groups)
    dot_plot_data$celltypes <- factor(dot_plot_data$celltype, levels = celltypes)
    
    p <- ggplot(dot_plot_data, aes_string(x = x, y = "beta", group = "peak_gene_pair", size = "-log10(fdr)")) +
        geom_hline(yintercept = 0, linetype = "solid", color = "black", alpha = 0.7) +
        geom_point(aes(color = if (length(celltypes) > 1) "celltype" else NULL), alpha = 0.6) +
        scale_color_brewer(palette = "Set1") +
        theme_minimal() +
        labs(title = paste(gene, if (length(celltypes) == 1) celltypes else "", if (length(groups) == 1) groups else ""),
             x = if (x == "group") "Group" else "Cell Type",
             y = "Beta Value",
             color = if (x == "group" & length(celltypes) > 1) "Cell Type" else NULL,
             size = "-log10(FDR)") +
        theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
        scale_x_discrete(limits = if (x == "group") groups else celltypes)

    if (length(celltypes) == 1 | length(groups) == 1) {p <- p + geom_line(aes(group = peak_gene_pair), alpha = 0.4, lwd = 0.5)}
    
    dot_plot_file <- file.path(plot_dir, paste0(tolower(gene), "_dot_plot_beta_values.jpg"))
    ggsave(dot_plot_file, plot = p, width = 8, height = 6)
}

plot_gene_beta_values("TBR1", groups, c("EN-Mature"), plot_dir, x="group")
plot_gene_beta_values("BCL11B", groups, c("EN-Mature"), plot_dir, x="group")
plot_gene_beta_values("SATB2", groups, c("EN-Mature"), plot_dir, x="group")

plot_gene_beta_values("SATB2", c("First_trimester"), celltypes, plot_dir, x="celltype")
plot_gene_beta_values("SATB2", c("Second_trimester"), celltypes, plot_dir, x="celltype")

plot_gene_beta_values("TBR1", c("First_trimester"), celltypes, plot_dir, x="celltype")
plot_gene_beta_values("TBR1", c("Second_trimester"), celltypes, plot_dir, x="celltype")

plot_gene_beta_values("BCL11B", c("Second_trimester"), celltypes, plot_dir, x="celltype")

plot_gene_beta_values("NEUROD2", c("Second_trimester"), celltypes, plot_dir, x="celltype")
```


```{r}
# study peaks which cross from positive to negative beta
scent_results_signif_t2 <- scent_results_signif[scent_results_signif$group == "Second_trimester", ]
# Identify peak_gene_pairs with positive beta in one cell type and negative beta in another

crossing_peak_gene_pairs <- scent_results_signif_t2 %>%
    dplyr::select(peak_gene_pair, celltype, beta) %>%
    tidyr::spread(key = celltype, value = beta, fill = NA) %>%
    dplyr::filter(if_any(-1, ~ . > 0) & if_any(-1, ~ . < 0))

crossing_peak_gene_pairs[is.na(crossing_peak_gene_pairs)] <- 0

crossing_long <- crossing_peak_gene_pairs %>%
    tidyr::gather(key = "celltype", value = "beta", -peak_gene_pair)

p <- ggplot(crossing_long, aes(x = celltype, y = beta, group = peak_gene_pair)) +
    geom_line(alpha = 0.5) +
    geom_point(size = 1) +
    theme_minimal() +
    labs(title = "Beta Values for Crossing Peak-Gene Pairs",
            x = "Cell Type",
            y = "Beta Value") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

crossing_plot_file <- file.path(plot_dir, "crossing_peak_gene_pairs_beta_values.jpg")
ggsave(crossing_plot_file, plot = p, width = 8, height = 6)
```

```{r}
# compute shared peak-gene pairs and Jaccard index across groups/celltypes
compute_shared_pairs <- function(result, group.by) {
    if (group.by == "celltype") {
        unique_groups <- unique(celltypes_groups$celltype)
    } else if (group.by == "group") {
        unique_groups <- unique(celltypes_groups$group)
    } else if (group.by == "celltypes_groups") {
        unique_groups <- paste(celltypes_groups$celltype, celltypes_groups$group, sep = "_")
    } else {
        stop("Invalid group.by value. Choose from 'celltype', 'group', or 'celltypes_groups'.")
    }

    shared_peaks_matrix <- matrix(0, nrow = length(unique_groups), ncol = length(unique_groups))
    jaccard_matrix <- matrix(0, nrow = length(unique_groups), ncol = length(unique_groups))

    rownames(shared_peaks_matrix) <- colnames(shared_peaks_matrix) <- unique_groups
    rownames(jaccard_matrix) <- colnames(jaccard_matrix) <- unique_groups

    for (i in 1:length(unique_groups)) {
        for (j in 1:length(unique_groups)) {
            if (group.by == "celltype") {
                peaks_i <- scent_results_signif[scent_results_signif$celltype == unique_groups[i], "peak_gene_pair"]
                peaks_j <- scent_results_signif[scent_results_signif$celltype == unique_groups[j], "peak_gene_pair"]
            } else if (group.by == "group") {
                peaks_i <- scent_results_signif[scent_results_signif$group == unique_groups[i], "peak_gene_pair"]
                peaks_j <- scent_results_signif[scent_results_signif$group == unique_groups[j], "peak_gene_pair"]
            } else if (group.by == "celltypes_groups") {
                celltype_group_i <- strsplit(unique_groups[i], "_")[[1]]
                celltype_group_j <- strsplit(unique_groups[j], "_")[[1]]
                peaks_i <- scent_results_signif[scent_results_signif$celltype == celltype_group_i[1] & 
                                                   scent_results_signif$group == celltype_group_i[2], "peak_gene_pair"]
                peaks_j <- scent_results_signif[scent_results_signif$celltype == celltype_group_j[1] & 
                                                   scent_results_signif$group == celltype_group_j[2], "peak_gene_pair"]
            }

            shared_peaks <- intersect(peaks_i, peaks_j)
            shared_peaks_matrix[i, j] <- length(shared_peaks)
            jaccard_matrix[i, j] <- length(shared_peaks) / length(union(peaks_i, peaks_j))
        }
    }

    return(list(shared_peaks_matrix = shared_peaks_matrix, jaccard_matrix = jaccard_matrix))
}
```

# shared peak gene pairs across groups
```{r}
shared_by_celltype <- compute_shared_pairs(scent_results_signif_df, group.by = "celltype")
shared_by_groups <- compute_shared_pairs(scent_results_signif_df, group.by = "group")
heatmap_data <- compute_shared_pairs(scent_results_signif_df, group.by = "celltypes_groups")

heatmap_data <- melt(shared_peaks_matrix)
colnames(heatmap_data) <- c("CellGroup1", "CellGroup2", "SharedPeaks")
heatmap_data$JaccardIndex <- melt(jaccard_matrix)$value

heatmap_data$CellGroup1 <- factor(heatmap_data$CellGroup1, levels = (paste(celltypes_groups$celltype, celltypes_groups$group, sep = "_")))
heatmap_data$CellGroup2 <- factor(heatmap_data$CellGroup2, levels = rev(paste(celltypes_groups$celltype, celltypes_groups$group, sep = "_")))

p <- ggplot(heatmap_data, aes(x = CellGroup1, y = CellGroup2, fill = JaccardIndex)) +
    geom_tile() +
    geom_text(aes(label = round(JaccardIndex, 2)), color = "white", size = 3) +
    scale_fill_viridis_c(option = "viridis", name = "Jaccard Index") +
    theme_minimal() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    labs(title = "Heatmap of Jaccard Index for Common Peak-Gene Pairs", x = "Cell-Group Pair 1", y = "Cell-Group Pair 2") +
    
    geom_vline(xintercept = cumsum(rev(table(celltypes_groups$group))) + 0.5, color = "white", linetype = "dashed") +
    geom_hline(yintercept = cumsum(table(celltypes_groups$group)) + 0.5, color = "white", linetype = "dashed") +
    
    geom_tile(data = subset(heatmap_data, as.numeric(CellGroup1) + as.numeric(CellGroup2) < dim(celltypes_groups)[1]+1), fill = "white", color = "white")

heatmap_file <- file.path(plot_dir, "heatmap_common_peak_gene_pairs.jpg")
ggsave(heatmap_file, plot = p, width = 10, height = 8)
```

```{r}
library(dplyr)
scent_results_signif_mature <- scent_results_signif[scent_results_signif$celltype == "EN-Mature", ]
scent_results_signif_mature$group <- factor(scent_results_signif_mature$group, levels = groups)
beta_tracking <- scent_results_signif_mature %>%
    dplyr::select(peak_gene_pair, group, beta) %>%
    tidyr::spread(key = group, value = beta, fill = 0)
head(beta_tracking)

beta_matrix <- as.matrix(beta_tracking[, -1]) 
rownames(beta_matrix) <- beta_tracking$peak_gene_pair

sil_width <- numeric(10)
for (k in 6:10) {
    print(k)
    pam_fit <- pam(beta_matrix, k = k)
    sil_width[k] <- pam_fit$silinfo$avg.width
}
optimal_k <- which.max(sil_width)

optimal_k <- 4

pam_fit <- pam(beta_matrix, k = optimal_k)
beta_tracking$cluster <- pam_fit$clustering

centroids <- aggregate(beta_matrix, by = list(cluster = beta_tracking$cluster), FUN = mean)
centroids_long <- reshape2::melt(centroids, id.vars = "cluster", variable.name = "group", value.name = "beta")

p <- ggplot(centroids_long, aes(x = group, y = beta, color = factor(cluster), group = cluster)) +
    geom_line(size = 1) +
    geom_point(size = 2) +
    scale_color_viridis_d(name = "Cluster") +
    theme_minimal() +
    labs(title = "Cluster Centroids of Beta Trajectories", x = "Group", y = "Beta") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1))

centroid_plot_file <- file.path(plot_dir, "cluster_centroids_beta_trajectories.jpg")
ggsave(centroid_plot_file, plot = p, width = 8, height = 6)
```

# gene ontology analysis of gene-enhancer pairs which are differentially active in each group

# see whether any genes have multiple peaks with different activation patterns

```{r}
# marker proportions across celltypes
group <- "Second_trimester"

marker_proportions <- list()
for (celltype in unique(celltypes_groups[, "celltype"])) {
    marker_hits <- data.frame(marker = celltype_markers[[celltype]],

    for (celltype in unique(celltypes_groups[, "celltype"])) {
        data <- scent_results[[celltype]][[group]]

    marker_proportions[[celltype]] <- sapply(markers, function(gene) {
        data <- scent_results[[celltype]][[group]]
        gene_data <- data[data$gene == gene, ]
        prop_significant <- sum(gene_data$p_val_adj < 0.01) / nrow(gene_data)
        return(prop_significant)
    })
}
```

```{r}
# volcano plots
directory <- file.path(plot_dir, "volcanos"); if (!dir.exists(directory)) { dir.create(directory, recursive = TRUE) }
for (celltype in unique(celltypes_groups[, "celltype"])) {
    for (group in unique(celltypes_groups[celltypes_groups$celltype == celltype, "group"])) {
        data <- scent_results[[celltype]][[group]]
        data$log_fdr <- -log10(data$p_val_adj)
        jpeg(file = file.path(directory, paste0(celltype, "_", group, ".jpg")))
        plot(data$beta, data$log_fdr, 
             xlab = "Beta", 
             ylab = "-log10(p_val_adj)", 
             main = paste("Volcano Plot:", celltype, group),
             pch = 20, 
             col = ifelse(data$gene %in% celltype_markers[[celltype]], "blue", "black"))
        abline(h = -log10(0.05), col = "red", lty = 2)
        dev.off()
    }
}
```