# load SCENT results
```{r}
library(ggplot2)
library(reshape2)
library(cluster)
library(dplyr)

base <- "/media/chang/HDD-8/joseph/bmi206/wangDev"
plot_dir <- "/home/joseph/R/bmi206/joseph/plots/wang"

celltypes <- c("Radial glia", "IPC-EN", "EN-Newborn", "EN-Immature", "EN-Mature")
groups <- c("First_trimester", "Second_trimester", "Third_trimester", "Infancy", "Adolescence")

celltypes_groups <- expand.grid(celltype = celltypes, group = groups, stringsAsFactors = FALSE)
celltypes_groups[celltypes_groups$celltype %in% c("Radial glia", "IPC-EN") & celltypes_groups$group %in% c("Third_trimester", "Infancy", "Adolescence"), ] <- NA

celltypes_groups[celltypes_groups$celltype %in% c("EN-Newborn", "EN-Immature") & celltypes_groups$group %in% c("Third_trimester", "Infancy", "Childhood", "Adolescence"), ] <- NA

celltypes_groups <- na.omit(celltypes_groups)

celltypes_groups <- celltypes_groups[order(match(celltypes_groups$group, groups), match(celltypes_groups$celltype, celltypes)), ]

celltype_markers <- lapply(unique(celltypes_groups$celltype), function(celltype) {
    data.frame(celltype = celltype, marker = read.csv(file.path(plot_dir, "markers", paste0("top_50_", celltype, "_markers.csv")))$gene)
}) %>% bind_rows()

group_markers <- lapply(unique(celltypes_groups$group), function(group) {
    data.frame(group = group, marker = read.csv(file.path(plot_dir, "markers", paste0("top_50_", group, "_markers.csv")))$gene)
}) %>% bind_rows()

all_markers <- unique(c(celltype_markers$marker, group_markers$marker))

# combine batches for each group and celltype
for (group in groups) {
    for (celltype in celltypes) {
        files <- list.files(path = file.path(base, "scent_results"), pattern = paste(celltype, group, sep="_"), full.names = TRUE)
        files <- files[grepl("\\d+\\.txt$", basename(files))]
        if (length(files) > 0) {
            combined_data <- do.call(rbind, lapply(files, read.table, header = TRUE))
            output_file <- file.path(base, "scent_results", paste0("SCENTresult_", celltype, "_", group, ".txt"))
            write.table(combined_data, file = output_file, row.names = FALSE, col.names = TRUE, quote = FALSE)
            print(paste("Combined SCENT results for", celltype, group))
        }
    }
}
```

```{r}
# load all results into a list
scent_results <- list()
for (celltype in unique(celltypes_groups[, "celltype"])) {
    print(celltype)
    scent_results[[celltype]] <- list()
    for (group in unique(celltypes_groups[celltypes_groups$celltype == celltype, "group"])) {
        print(group)
        scent_results[[celltype]][[group]] <- read.table(file.path(base, "scent_results", paste0("SCENTresult_", celltype, "_", group, ".txt")), header = TRUE)
    }
}

scent_results <- do.call(rbind, lapply(names(scent_results), function(celltype) {
    do.call(rbind, lapply(names(scent_results[[celltype]]), function(group) {
        data <- scent_results[[celltype]][[group]]
        data$celltype <- celltype
        data$group <- group
        # Ensure consistent column names
        required_cols <- c("celltype", "group", "gene", "peak", "beta", "p")
        missing_cols <- setdiff(required_cols, colnames(data))
        data[missing_cols] <- NA
        return(data[, required_cols])
    }))
}))

# adult_results <- read.table(file.path(base, "scent_results/Brain_allqced_bootpkg_nopc_allCT.FDR0.10.txt"), header = TRUE)
# adult_results <- adult_results[(adult_results$celltype == "EXCNEU") & (adult_results$gene %in% all_markers), ]
# adult_results <- adult_results %>% mutate(group = "Adult", celltype = "EN-Mature") %>%
#                         select(celltype, group, gene, peak, beta, p)
# scent_results <- rbind(scent_results, adult_results)

scent_results$fdr <- p.adjust(scent_results$p, method = "BH")

groups <- c("First_trimester", "Second_trimester", "Third_trimester", "Infancy", "Adolescence")

# Merge overlapping peaks
library(GenomicRanges)
peak_ranges <- GRanges(seqnames = "chr1", 
                       ranges = IRanges(start = as.numeric(sub(".*-(\\d+)-\\d+$", "\\1", scent_results$peak)),
                                        end = as.numeric(sub(".*-\\d+-(\\d+)$", "\\1", scent_results$peak))))
merged_peaks <- reduce(peak_ranges)

peak_map <- findOverlaps(peak_ranges, merged_peaks)
scent_results$merged_peak <- as.character(merged_peaks[subjectHits(peak_map)])
scent_results <- scent_results[order(scent_results$fdr), ] # remove duplicates, keeping lowest fdr
scent_results <- scent_results[!duplicated(scent_results[, c("celltype", "group", "merged_peak")]), ]
scent_results$peak_gene_pair <- paste(scent_results$merged_peak, scent_results$gene, sep = "_")

scent_results_signif <- scent_results[scent_results$fdr < 0.05, ]

head(scent_results_signif)

scent_results_signif[scent_results_signif$gene == "BCL11B",]
```

# plot SCENT results summary (Figure 1A,D)
```{r}
peak_counts <- scent_results_signif %>%
    group_by(celltype, group) %>%
    summarise(num_peaks = n(), .groups = "drop")

peak_counts$group <- factor(peak_counts$group, levels = groups)
peak_counts$celltype <- factor(peak_counts$celltype, levels = celltypes)

p <- ggplot(peak_counts, aes(x = group, y = num_peaks, fill = celltype)) +
    geom_bar(stat = "identity", position = "dodge") +
    theme_minimal() +
    labs(x = "Age Group",
         y = "Number of Peaks (FDR < 0.05)",
         fill = "Cell Type") +
    theme_minimal(base_size = 16) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
            axis.text.y = element_text(size = 14),
            axis.title = element_text(size = 16),
            legend.text = element_text(size = 14),
            legend.title = element_text(size = 16),
            panel.grid = element_blank())

bar_plot_file <- file.path(plot_dir, "num_peaks_bar_plot.jpg")
ggsave(bar_plot_file, plot = p, width = 12, height = 6)

dotplot_data <- scent_results_signif %>%
    dplyr::select(peak_gene_pair, group, celltype, beta) %>%
    mutate(group = factor(group, levels = groups),
           celltype = factor(celltype, levels = celltypes))

p <- ggplot(dotplot_data, aes(x = group, y = beta, fill = celltype)) +
    geom_violin(alpha = 0.6) +
    theme_minimal() +
    labs(x = "Group",
         y = "Beta Value (FDR < 0.05)",
         fill = "Cell Type") +
    theme(axis.text.x = element_text(angle = 45, hjust = 1, size = 14),
            axis.text.y = element_text(size = 14),
            axis.title = element_text(size = 16),
            legend.text = element_text(size = 14),
            legend.title = element_text(size = 16))

dotplot_file <- file.path(plot_dir, "violinplot_betas_by_group_and_celltype.jpg")
ggsave(dotplot_file, plot = p, width = 12, height = 6)
```

# bootstrapped Jaccard index (Figure 1B-C)
```{r}
jaccard_index <- function(set1, set2) {
    intersection <- length(intersect(set1, set2))
    union <- length(union(set1, set2))
    if (union == 0) {
        return(0)
    } else {
        return(intersection / union)
    }
}

scent_results_signif_mature <- scent_results_signif[scent_results_signif$celltype == "EN-Mature", ]
scent_results_signif_t1 <- scent_results_signif[scent_results_signif$group == "First_trimester", ]
scent_results_signif_t2 <- scent_results_signif[scent_results_signif$group == "Second_trimester", ]

peak_gene_pairs_mature_refgroup <- scent_results_signif_mature$peak_gene_pair[scent_results_signif_mature$group == "Adolescence"]
peak_gene_pairs_t1_refgroup <- scent_results_signif_t1$peak_gene_pair[scent_results_signif_t1$celltype == "EN-Mature"]
peak_gene_pairs_t2_refgroup <- scent_results_signif_t2$peak_gene_pair[scent_results_signif_t2$celltype == "EN-Mature"]

group_jac_ind <- data.frame(group = groups, jaccard_index = NA)
t1_jac_ind <- data.frame(celltype = celltypes, jaccard_index = NA)
t2_jac_ind <- data.frame(celltype = celltypes, jaccard_index = NA)

set.seed(123)
bootstrap_jaccard <- function(ref_set, comp_set, n = 1000) {
    bootstrapped_indices <- replicate(n, sample(seq_along(ref_set), length(ref_set), replace = TRUE))
    bootstrapped_jaccard <- apply(bootstrapped_indices, 2, function(indices) {
        jaccard_index(ref_set[indices], comp_set)
    })
    return(bootstrapped_jaccard)
}

for (group in groups) {
    scent_results_signif_mature_group <- scent_results_signif_mature[scent_results_signif_mature$group == group, ]
    peak_gene_pairs_group <- scent_results_signif_mature_group$peak_gene_pair
    bootstrapped_jaccard_values <- bootstrap_jaccard(peak_gene_pairs_mature_refgroup, peak_gene_pairs_group)
    group_jac_ind$jaccard_index[group_jac_ind$group == group] <- mean(bootstrapped_jaccard_values)
    group_jac_ind$ci_lower[group_jac_ind$group == group] <- quantile(bootstrapped_jaccard_values, 0.01)
    group_jac_ind$ci_upper[group_jac_ind$group == group] <- quantile(bootstrapped_jaccard_values, 0.99)
}

for (celltype in celltypes) {
    scent_results_signif_t1_celltype <- scent_results_signif_t1[scent_results_signif_t1$celltype == celltype, ]
    peak_gene_pairs_celltype <- scent_results_signif_t1_celltype$peak_gene_pair
    bootstrapped_jaccard_values <- bootstrap_jaccard(peak_gene_pairs_t1_refgroup, peak_gene_pairs_celltype)
    t1_jac_ind$jaccard_index[t1_jac_ind$celltype == celltype] <- mean(bootstrapped_jaccard_values)
    t1_jac_ind$ci_lower[t1_jac_ind$celltype == celltype] <- quantile(bootstrapped_jaccard_values, 0.005)
    t1_jac_ind$ci_upper[t1_jac_ind$celltype == celltype] <- quantile(bootstrapped_jaccard_values, 0.995)

    scent_results_signif_t2_celltype <- scent_results_signif_t2[scent_results_signif_t2$celltype == celltype, ]
    peak_gene_pairs_celltype <- scent_results_signif_t2_celltype$peak_gene_pair
    bootstrapped_jaccard_values <- bootstrap_jaccard(peak_gene_pairs_t2_refgroup, peak_gene_pairs_celltype)
    t2_jac_ind$jaccard_index[t2_jac_ind$celltype == celltype] <- mean(bootstrapped_jaccard_values)
    t2_jac_ind$ci_lower[t2_jac_ind$celltype == celltype] <- quantile(bootstrapped_jaccard_values, 0.005)
    t2_jac_ind$ci_upper[t2_jac_ind$celltype == celltype] <- quantile(bootstrapped_jaccard_values, 0.995)
}

plot_jaccard_index <- function(jaccard_data, output_file, x = "group") {
    if (x == "group") {
        jaccard_data$group <- factor(jaccard_data$group, levels = groups)
        x_label <- "Group"
    } else if (x == "celltype") {
        jaccard_data$celltype <- factor(jaccard_data$celltype, levels = celltypes)
        x_label <- "Cell Type"
    } else {
        stop("Invalid x value. Choose either 'group' or 'celltype'.")
    }

    if (x == "group") {
        jaccard_data[,-1] <- jaccard_data[,-1]/jaccard_data$jaccard_index[jaccard_data$group == "Adolescence"]
        jaccard_data$ci_lower[jaccard_data$group == "Adolescence"] <- NA
        jaccard_data$ci_upper[jaccard_data$group == "Adolescence"] <- NA
    } else {
        jaccard_data[,-1] <- jaccard_data[,-1]/jaccard_data$jaccard_index[jaccard_data$celltype == "EN-Mature"]
        jaccard_data$ci_lower[jaccard_data$celltype == "EN-Mature"] <- NA
        jaccard_data$ci_upper[jaccard_data$celltype == "EN-Mature"] <- NA
    }
    
    p <- ggplot(jaccard_data, aes_string(x = x, y = "jaccard_index", fill = x)) +
        geom_bar(stat = "identity", position = "dodge") +
        geom_errorbar(aes(ymin = ci_lower, ymax = ci_upper), width = 0.2, position = position_dodge(0.9)) +
        theme_minimal() +
        # scale_fill_brewer(palette = "Set2") +
        labs(x = x_label,
             y = "Jaccard index",
             fill = x_label) +
        theme(axis.text.x = element_text(angle = 35, hjust = 1, size = 14),
              axis.text.y = element_text(size = 14),
              axis.title = element_text(size = 16),
              legend.text = element_text(size = 14),
              legend.title = element_text(size = 16)) +
        annotate("text", x = 1.5, y = 0.3, label = "ns", size = 5) +
        annotate("segment", x = 1, xend = 2, y = 0.25, yend = 0.25, color = "black") +
        annotate("text", x = 2.5, y = 0.55, label = "p < 0.01", size = 5) +
        annotate("segment", x = 2, xend = 3, y = 0.5, yend = 0.5, color = "black") +
        annotate("text", x = 3.5, y = 0.75, label = "p < 0.01", size = 5) +
        annotate("segment", x = 3, xend = 4, y = 0.7, yend = 0.7, color = "black")
    
    ggsave(output_file, plot = p, width = 12, height = 4)
}

plot_jaccard_index(group_jac_ind, file.path(plot_dir, "jaccard_index_bootstrap.jpg"), x = "group")
plot_jaccard_index(t2_jac_ind, file.path(plot_dir, "jaccard_index_t2_bootstrap.jpg"), x = "celltype")

# # spearman correlation
# # permutation test: scramble peak-gene pairs across celltypes
# # regress out number of cells
```

# linear regression of effect size onto cell type (Figure 1E, right)
```{r}
scent_results_signif_query <- scent_results_signif[scent_results_signif$group == "Second_trimester", ]
scent_results_signif_ref <- scent_results_signif[scent_results_signif$celltype == "EN-Mature" & 
                                                       scent_results_signif$group == "Second_trimester" &
                                                       scent_results_signif$beta > 0, ]                                                      

beta_matrix <- data.frame(peak_gene_pair = scent_results_signif_ref$peak_gene_pair)
for (celltype in celltypes) {
    # beta_matrix[[celltype]] <- abs(scent_results_signif_query$beta[match(beta_matrix$peak_gene_pair,
    #                                                     scent_results_signif_query$peak_gene_pair[scent_results_signif_query$celltype == celltype])])
    beta_matrix[[celltype]] <- scent_results_signif_query$beta[match(beta_matrix$peak_gene_pair,
                                                        scent_results_signif_query$peak_gene_pair[scent_results_signif_query$celltype == celltype])]                                                        
}

beta_matrix[is.na(beta_matrix)] <- 0
rownames(beta_matrix) <- beta_matrix$peak_gene_pair
beta_matrix$peak_gene_pair <- NULL
beta_matrix <- sweep(beta_matrix, 1, rowMeans(beta_matrix), FUN = "-")
beta_matrix <- beta_matrix * sign(beta_matrix[,"EN-Mature"])

beta_matrix <- beta_matrix[, !colnames(beta_matrix) %in% "EN-Mature"]

# linear regression for each row of beta_matrix
linear_regression_slope <- apply(beta_matrix, 1, function(row) {
    group_numeric <- as.numeric(factor(colnames(beta_matrix), levels = celltypes))
    lm_model <- lm(row ~ group_numeric)
    return(coef(lm_model)[2])  # Extract the slope
})

p <- ggplot(data.frame(slope = linear_regression_slope), aes(x = slope)) +
    geom_histogram(bins = 30, fill = "lightblue", color = "black", alpha = 0.7) +
    labs(title = "Distribution of Linear Regression Slopes",
         x = "Slope",
         y = "Frequency") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_text(hjust = 0.5))
ggsave(file.path(plot_dir, "linear_regression_slopes_histogram.jpg"), plot = p, width = 8, height = 6)

set.seed(123)
n_iterations <- 1000
bootstrap_slopes <- numeric(n_iterations)

for (i in 1:n_iterations) {
    print(i)
    boot_sample <- beta_matrix[sample(1:nrow(beta_matrix), replace = TRUE), ]

    boot_long <- boot_sample %>%
        tidyr::gather(key = "celltype", value = "beta") %>%
        mutate(group_numeric = as.numeric(factor(celltype, levels = celltypes)))

    lm_model <- lm(beta ~ group_numeric, data = boot_long)
    bootstrap_slopes[i] <- coef(lm_model)[2]
}

bootstrap_summary <- data.frame(
    mean_slope = mean(bootstrap_slopes),
    lower_ci = quantile(bootstrap_slopes, 0.025),
    upper_ci = quantile(bootstrap_slopes, 0.975)
)

print(bootstrap_summary)

p <- ggplot(data.frame(slope = bootstrap_slopes), aes(x = slope)) +
    geom_histogram(bins = 30, fill = "lightblue", color = "black", alpha = 0.7) +
    geom_vline(xintercept = 0, color = "black", linetype = "dashed", size = 0.8) +
    labs(x = "Slope", y = "Number of bootstraps") +
    theme_minimal(base_size = 14) +
    theme(plot.title = element_text(hjust = 0.5)) +
    theme(panel.grid = element_blank())

bootstrap_hist_file <- file.path(plot_dir, "bootstrap_slopes_histogram.jpg")
ggsave(bootstrap_hist_file, plot = p, width = 8, height = 4)
```

# heatmap of beta matrix (Figure 1E, left)
```{r}
#  hierarchical clustering on the beta matrix
dist_matrix <- dist(beta_matrix)
hclust_fit <- hclust(dist_matrix, method = "ward.D2")

library(pheatmap)

beta_matrix_ordered <- beta_matrix[hclust_fit$order, ]
beta_matrix_ordered$cluster <- NULL

dim(beta_matrix_ordered)

heatmap_file <- file.path(plot_dir, "beta_matrix_heatmap.jpg")
pheatmap(beta_matrix_ordered, 
         cluster_rows = TRUE, 
         cluster_cols = FALSE, 
         color = scales::gradient_n_pal(c("blue", "white", "red"))(seq(0, 1, length.out = 100)),
         fontsize = 12,
         show_rownames = FALSE,
         filename = heatmap_file,
         legend = TRUE,
         legend_labels = "Beta Value",
         width = 15)

```